-- 企业智融链交易档案表，增加列字段
ALTER TABLE ENTERPRISE_BILL_ARCHIVE ADD COLUMN
`FACTORING_ID` bigint(20) DEFAULT NULL COMMENT '保理商Id';
ALTER TABLE ENTERPRISE_BILL_ARCHIVE ADD COLUMN
`FUND_ID` bigint(20) DEFAULT NULL COMMENT '资金方ID';
